 assign htv_0 = (~sel) ? 
        ((({{n{hth_0[LENGTH]}},hth_0} + {{n{hth_8[LENGTH]}},hth_8 }) + ({{n{hth_4[LENGTH]}},hth_4 } + {{n{hth_12[LENGTH]}},hth_12})) +  (({{n{hth_2[LENGTH]}},hth_2 } + {{n{hth_10[LENGTH]}}, hth_10}) + ({{n{hth_6[LENGTH]}},hth_6 } + {{n{hth_14[LENGTH]}},hth_14 }))) + ((({{n{hth_1[LENGTH]}}, hth_1 } + {{n{hth_9[LENGTH]}},hth_9 }) + ({{n{hth_5[LENGTH]}},hth_5 }+ {{n{hth_13[LENGTH]}},hth_13 })) +  (({{n{hth_3[LENGTH]}},hth_3 } + {{n{hth_11[LENGTH]}},hth_11 }) + ({{n{hth_7[LENGTH]}},hth_7 } + {{n{hth_15[LENGTH]}},hth_15 })))
            :
        ((({{n{hth_0[LENGTH]}},hth_0} - {{n{hth_8[LENGTH]}},hth_8 }) + ({{n{hth_4[LENGTH]}},hth_4 } - {{n{hth_12[LENGTH]}},hth_12})) +  (({{n{hth_2[LENGTH]}},hth_2 } - {{n{hth_10[LENGTH]}}, hth_10}) + ({{n{hth_6[LENGTH]}},hth_6 } - {{n{hth_14[LENGTH]}},hth_14 }))) + ((({{n{hth_1[LENGTH]}}, hth_1 } - {{n{hth_9[LENGTH]}},hth_9 }) + ({{n{hth_5[LENGTH]}},hth_5 } - {{n{hth_13[LENGTH]}},hth_13 })) +  (({{n{hth_3[LENGTH]}},hth_3 } - {{n{hth_11[LENGTH]}},hth_11 }) + ({{n{hth_7[LENGTH]}},hth_7 } - {{n{hth_15[LENGTH]}},hth_15 })));
    assign htv_1 = (~sel) ? 
        ((({{n{hth_0[LENGTH]}},hth_0} + {{n{hth_8[LENGTH]}},hth_8 }) + ({{n{hth_4[LENGTH]}},hth_4 } + {{n{hth_12[LENGTH]}},hth_12})) +  (({{n{hth_2[LENGTH]}},hth_2 } + {{n{hth_10[LENGTH]}}, hth_10}) + ({{n{hth_6[LENGTH]}},hth_6 } + {{n{hth_14[LENGTH]}},hth_14 }))) - ((({{n{hth_1[LENGTH]}}, hth_1 } + {{n{hth_9[LENGTH]}},hth_9 }) + ({{n{hth_5[LENGTH]}},hth_5 }+ {{n{hth_13[LENGTH]}},hth_13 })) +  (({{n{hth_3[LENGTH]}},hth_3 } + {{n{hth_11[LENGTH]}},hth_11 }) + ({{n{hth_7[LENGTH]}},hth_7 } + {{n{hth_15[LENGTH]}},hth_15 })))
            :
        ((({{n{hth_0[LENGTH]}},hth_0} - {{n{hth_8[LENGTH]}},hth_8 }) + ({{n{hth_4[LENGTH]}},hth_4 } - {{n{hth_12[LENGTH]}},hth_12})) +  (({{n{hth_2[LENGTH]}},hth_2 } - {{n{hth_10[LENGTH]}}, hth_10}) + ({{n{hth_6[LENGTH]}},hth_6 } - {{n{hth_14[LENGTH]}},hth_14 }))) - ((({{n{hth_1[LENGTH]}}, hth_1 } - {{n{hth_9[LENGTH]}},hth_9 }) + ({{n{hth_5[LENGTH]}},hth_5 } - {{n{hth_13[LENGTH]}},hth_13 })) +  (({{n{hth_3[LENGTH]}},hth_3 } - {{n{hth_11[LENGTH]}},hth_11 }) + ({{n{hth_7[LENGTH]}},hth_7 } - {{n{hth_15[LENGTH]}},hth_15 })));
    assign htv_2 = (~sel) ? 
        ((({{n{hth_0[LENGTH]}},hth_0} + {{n{hth_8[LENGTH]}},hth_8 }) + ({{n{hth_4[LENGTH]}},hth_4 } + {{n{hth_12[LENGTH]}},hth_12})) -  (({{n{hth_2[LENGTH]}},hth_2 } + {{n{hth_10[LENGTH]}}, hth_10}) + ({{n{hth_6[LENGTH]}},hth_6 } + {{n{hth_14[LENGTH]}},hth_14 }))) + ((({{n{hth_1[LENGTH]}}, hth_1 } + {{n{hth_9[LENGTH]}},hth_9 }) + ({{n{hth_5[LENGTH]}},hth_5 }+ {{n{hth_13[LENGTH]}},hth_13 })) -  (({{n{hth_3[LENGTH]}},hth_3 } + {{n{hth_11[LENGTH]}},hth_11 }) + ({{n{hth_7[LENGTH]}},hth_7 } + {{n{hth_15[LENGTH]}},hth_15 })))
            :
        ((({{n{hth_0[LENGTH]}},hth_0} - {{n{hth_8[LENGTH]}},hth_8 }) + ({{n{hth_4[LENGTH]}},hth_4 } - {{n{hth_12[LENGTH]}},hth_12})) -  (({{n{hth_2[LENGTH]}},hth_2 } - {{n{hth_10[LENGTH]}}, hth_10}) + ({{n{hth_6[LENGTH]}},hth_6 } - {{n{hth_14[LENGTH]}},hth_14 }))) + ((({{n{hth_1[LENGTH]}}, hth_1 } - {{n{hth_9[LENGTH]}},hth_9 }) + ({{n{hth_5[LENGTH]}},hth_5 } - {{n{hth_13[LENGTH]}},hth_13 })) -  (({{n{hth_3[LENGTH]}},hth_3 } - {{n{hth_11[LENGTH]}},hth_11 }) + ({{n{hth_7[LENGTH]}},hth_7 } - {{n{hth_15[LENGTH]}},hth_15 })));
    assign htv_3 = (~sel) ? 
        ((({{n{hth_0[LENGTH]}},hth_0} + {{n{hth_8[LENGTH]}},hth_8 }) + ({{n{hth_4[LENGTH]}},hth_4 } + {{n{hth_12[LENGTH]}},hth_12})) -  (({{n{hth_2[LENGTH]}},hth_2 } + {{n{hth_10[LENGTH]}}, hth_10}) + ({{n{hth_6[LENGTH]}},hth_6 } + {{n{hth_14[LENGTH]}},hth_14 }))) - ((({{n{hth_1[LENGTH]}}, hth_1 } + {{n{hth_9[LENGTH]}},hth_9 }) + ({{n{hth_5[LENGTH]}},hth_5 }+ {{n{hth_13[LENGTH]}},hth_13 })) -  (({{n{hth_3[LENGTH]}},hth_3 } + {{n{hth_11[LENGTH]}},hth_11 }) + ({{n{hth_7[LENGTH]}},hth_7 } + {{n{hth_15[LENGTH]}},hth_15 })))
            :
        ((({{n{hth_0[LENGTH]}},hth_0} - {{n{hth_8[LENGTH]}},hth_8 }) + ({{n{hth_4[LENGTH]}},hth_4 } - {{n{hth_12[LENGTH]}},hth_12})) -  (({{n{hth_2[LENGTH]}},hth_2 } - {{n{hth_10[LENGTH]}}, hth_10}) + ({{n{hth_6[LENGTH]}},hth_6 } - {{n{hth_14[LENGTH]}},hth_14 }))) - ((({{n{hth_1[LENGTH]}}, hth_1 } - {{n{hth_9[LENGTH]}},hth_9 }) + ({{n{hth_5[LENGTH]}},hth_5 } - {{n{hth_13[LENGTH]}},hth_13 })) -  (({{n{hth_3[LENGTH]}},hth_3 } - {{n{hth_11[LENGTH]}},hth_11 }) + ({{n{hth_7[LENGTH]}},hth_7 } - {{n{hth_15[LENGTH]}},hth_15 })));
    assign htv_4 = (~sel) ? 
        ((({{n{hth_0[LENGTH]}},hth_0} + {{n{hth_8[LENGTH]}},hth_8 }) - ({{n{hth_4[LENGTH]}},hth_4 } + {{n{hth_12[LENGTH]}},hth_12})) +  (({{n{hth_2[LENGTH]}},hth_2 } + {{n{hth_10[LENGTH]}}, hth_10}) - ({{n{hth_6[LENGTH]}},hth_6 } + {{n{hth_14[LENGTH]}},hth_14 }))) + ((({{n{hth_1[LENGTH]}}, hth_1 } + {{n{hth_9[LENGTH]}},hth_9 }) - ({{n{hth_5[LENGTH]}},hth_5 }+ {{n{hth_13[LENGTH]}},hth_13 })) +  (({{n{hth_3[LENGTH]}},hth_3 } + {{n{hth_11[LENGTH]}},hth_11 }) - ({{n{hth_7[LENGTH]}},hth_7 } + {{n{hth_15[LENGTH]}},hth_15 })))
            :
        ((({{n{hth_0[LENGTH]}},hth_0} - {{n{hth_8[LENGTH]}},hth_8 }) - ({{n{hth_4[LENGTH]}},hth_4 } - {{n{hth_12[LENGTH]}},hth_12})) +  (({{n{hth_2[LENGTH]}},hth_2 } - {{n{hth_10[LENGTH]}}, hth_10}) - ({{n{hth_6[LENGTH]}},hth_6 } - {{n{hth_14[LENGTH]}},hth_14 }))) + ((({{n{hth_1[LENGTH]}}, hth_1 } - {{n{hth_9[LENGTH]}},hth_9 }) - ({{n{hth_5[LENGTH]}},hth_5 } - {{n{hth_13[LENGTH]}},hth_13 })) +  (({{n{hth_3[LENGTH]}},hth_3 } - {{n{hth_11[LENGTH]}},hth_11 }) - ({{n{hth_7[LENGTH]}},hth_7 } - {{n{hth_15[LENGTH]}},hth_15 })));
    assign htv_5 = (~sel) ? 
        ((({{n{hth_0[LENGTH]}},hth_0} + {{n{hth_8[LENGTH]}},hth_8 }) - ({{n{hth_4[LENGTH]}},hth_4 } + {{n{hth_12[LENGTH]}},hth_12})) +  (({{n{hth_2[LENGTH]}},hth_2 } + {{n{hth_10[LENGTH]}}, hth_10}) - ({{n{hth_6[LENGTH]}},hth_6 } + {{n{hth_14[LENGTH]}},hth_14 }))) - ((({{n{hth_1[LENGTH]}}, hth_1 } + {{n{hth_9[LENGTH]}},hth_9 }) - ({{n{hth_5[LENGTH]}},hth_5 }+ {{n{hth_13[LENGTH]}},hth_13 })) +  (({{n{hth_3[LENGTH]}},hth_3 } + {{n{hth_11[LENGTH]}},hth_11 }) - ({{n{hth_7[LENGTH]}},hth_7 } + {{n{hth_15[LENGTH]}},hth_15 })))
            :
        ((({{n{hth_0[LENGTH]}},hth_0} - {{n{hth_8[LENGTH]}},hth_8 }) - ({{n{hth_4[LENGTH]}},hth_4 } - {{n{hth_12[LENGTH]}},hth_12})) +  (({{n{hth_2[LENGTH]}},hth_2 } - {{n{hth_10[LENGTH]}}, hth_10}) - ({{n{hth_6[LENGTH]}},hth_6 } - {{n{hth_14[LENGTH]}},hth_14 }))) - ((({{n{hth_1[LENGTH]}}, hth_1 } - {{n{hth_9[LENGTH]}},hth_9 }) - ({{n{hth_5[LENGTH]}},hth_5 } - {{n{hth_13[LENGTH]}},hth_13 })) +  (({{n{hth_3[LENGTH]}},hth_3 } - {{n{hth_11[LENGTH]}},hth_11 }) - ({{n{hth_7[LENGTH]}},hth_7 } - {{n{hth_15[LENGTH]}},hth_15 })));
    assign htv_6 = (~sel) ? 
        ((({{n{hth_0[LENGTH]}},hth_0} + {{n{hth_8[LENGTH]}},hth_8 }) - ({{n{hth_4[LENGTH]}},hth_4 } + {{n{hth_12[LENGTH]}},hth_12})) -  (({{n{hth_2[LENGTH]}},hth_2 } + {{n{hth_10[LENGTH]}}, hth_10}) - ({{n{hth_6[LENGTH]}},hth_6 } + {{n{hth_14[LENGTH]}},hth_14 }))) + ((({{n{hth_1[LENGTH]}}, hth_1 } + {{n{hth_9[LENGTH]}},hth_9 }) - ({{n{hth_5[LENGTH]}},hth_5 }+ {{n{hth_13[LENGTH]}},hth_13 })) -  (({{n{hth_3[LENGTH]}},hth_3 } + {{n{hth_11[LENGTH]}},hth_11 }) - ({{n{hth_7[LENGTH]}},hth_7 } + {{n{hth_15[LENGTH]}},hth_15 })))
            :
        ((({{n{hth_0[LENGTH]}},hth_0} - {{n{hth_8[LENGTH]}},hth_8 }) - ({{n{hth_4[LENGTH]}},hth_4 } - {{n{hth_12[LENGTH]}},hth_12})) -  (({{n{hth_2[LENGTH]}},hth_2 } - {{n{hth_10[LENGTH]}}, hth_10}) - ({{n{hth_6[LENGTH]}},hth_6 } - {{n{hth_14[LENGTH]}},hth_14 }))) + ((({{n{hth_1[LENGTH]}}, hth_1 } - {{n{hth_9[LENGTH]}},hth_9 }) - ({{n{hth_5[LENGTH]}},hth_5 } - {{n{hth_13[LENGTH]}},hth_13 })) -  (({{n{hth_3[LENGTH]}},hth_3 } - {{n{hth_11[LENGTH]}},hth_11 }) - ({{n{hth_7[LENGTH]}},hth_7 } - {{n{hth_15[LENGTH]}},hth_15 })));
    assign htv_7 = (~sel) ? 
        ((({{n{hth_0[LENGTH]}},hth_0} + {{n{hth_8[LENGTH]}},hth_8 }) - ({{n{hth_4[LENGTH]}},hth_4 } + {{n{hth_12[LENGTH]}},hth_12})) -  (({{n{hth_2[LENGTH]}},hth_2 } + {{n{hth_10[LENGTH]}}, hth_10}) - ({{n{hth_6[LENGTH]}},hth_6 } + {{n{hth_14[LENGTH]}},hth_14 }))) - ((({{n{hth_1[LENGTH]}}, hth_1 } + {{n{hth_9[LENGTH]}},hth_9 }) - ({{n{hth_5[LENGTH]}},hth_5 }+ {{n{hth_13[LENGTH]}},hth_13 })) -  (({{n{hth_3[LENGTH]}},hth_3 } + {{n{hth_11[LENGTH]}},hth_11 }) - ({{n{hth_7[LENGTH]}},hth_7 } + {{n{hth_15[LENGTH]}},hth_15 })))
                :
        ((({{n{hth_0[LENGTH]}},hth_0} - {{n{hth_8[LENGTH]}},hth_8 }) - ({{n{hth_4[LENGTH]}},hth_4 } - {{n{hth_12[LENGTH]}},hth_12})) -  (({{n{hth_2[LENGTH]}},hth_2 } - {{n{hth_10[LENGTH]}}, hth_10}) - ({{n{hth_6[LENGTH]}},hth_6 } - {{n{hth_14[LENGTH]}},hth_14 }))) - ((({{n{hth_1[LENGTH]}}, hth_1 } - {{n{hth_9[LENGTH]}},hth_9 }) - ({{n{hth_5[LENGTH]}},hth_5 } - {{n{hth_13[LENGTH]}},hth_13 })) -  (({{n{hth_3[LENGTH]}},hth_3 } - {{n{hth_11[LENGTH]}},hth_11 }) - ({{n{hth_7[LENGTH]}},hth_7 } - {{n{hth_15[LENGTH]}},hth_15 })));
