# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/aluno/Desktop/gitapagar/SATD-research/pipeline_atraso/pipeline_atraso.srcs/sources_1/ip/mult_pipe/mult_pipe.xci
# IP: The module: 'mult_pipe' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aluno/Desktop/gitapagar/SATD-research/pipeline_atraso/pipeline_atraso.gen/sources_1/ip/mult_pipe/mult_pipe_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_pipe'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/aluno/Desktop/gitapagar/SATD-research/pipeline_atraso/pipeline_atraso.srcs/sources_1/ip/mult_pipe/mult_pipe.xci
# IP: The module: 'mult_pipe' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aluno/Desktop/gitapagar/SATD-research/pipeline_atraso/pipeline_atraso.gen/sources_1/ip/mult_pipe/mult_pipe_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_pipe'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
