# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7k70tfbg676-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/juliana/Documentos/GitHub/SATD-research/Vivado/SATD/SATD.cache/wt [current_project]
set_property parent.project_path /home/juliana/Documentos/GitHub/SATD-research/Vivado/SATD/SATD.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/juliana/Documentos/GitHub/SATD-research/ISE/SATD/differences.v
  /home/juliana/Documentos/GitHub/SATD-research/ISE/SATD/control_satd.v
  /home/juliana/Documentos/GitHub/SATD-research/ISE/SATD/SATD.v
  /home/juliana/Documentos/GitHub/SATD-research/ISE/SATD/SATD_tb.v
}
catch { write_hwdef -file SATD_tb.hwdef }
synth_design -top SATD_tb -part xc7k70tfbg676-1
write_checkpoint -noxdef SATD_tb.dcp
catch { report_utilization -file SATD_tb_utilization_synth.rpt -pb SATD_tb_utilization_synth.pb }
